# Site settings
title: Chris Tan. Maker, NYC.
email: csytan@gmail.com
description: Chris Tan's personal website.
url: https://csytan.com
enforce_ssl: csytan.com
twitter_username: csytan
github_username: csytan

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter: pygments